### ISSUE TITLE
CUDA_HOME not found

### ISSUE THREAD

**Issue by forresti** [nerfstudio-project/gsplat#197]
I am trying to install gsplat in such a way that I can edit the code.
On Linux, after I clone gsplat, I do `pip install -e .`. It fails with:
```
Obtaining file:///home/ubuntu/code/gsplat
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/code/gsplat/setup.py", line 133, in <module>
          ext_modules=get_extensions() if not BUILD_NO_CUDA else [],
                      ^^^^^^^^^^^^^^^^
        File "/home/ubuntu/code/gsplat/setup.py", line 90, in get_extensions
          extension = CUDAExtension(
                      ^^^^^^^^^^^^^^
        File "/home/ubuntu/anaconda3/envs/gsplat/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ubuntu/anaconda3/envs/gsplat/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ubuntu/anaconda3/envs/gsplat/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I also try:
```
export CUDA_HOME=/usr/local/cuda-11.8
pip install -e .
```
But I get the same error.

**Comment by liruilong940607** [comment]
May be try some solutions from [here](https://github.com/conda/conda/issues/7757)? Without accessing your environment it's a bit hard to diagnose as it is clearly an environment issue.

**Comment by forresti** [comment]
I figured it out. My mistake is that I accidentally installed pytorch without cuda, and cpp_extension.py behaves differently without pytorch-cuda. Fixed it by making a new env with pytorch-cuda.
