### ISSUE TITLE
UnboundLocalError with _torch_impl.rasterize_forward

### ISSUE THREAD

**Issue by ymtoo** [nerfstudio-project/gsplat#201]
```python
import torch
from gsplat._torch_impl import rasterize_forward

num_points = 100
img_width = 512
img_height = 512
block_width = 16

tile_bounds = ((img_width + block_width - 1) // block_width,
	       (img_height + block_width - 1) // block_width,
	       1)
block = (block_width, block_width, 1)
img_size = (img_width, img_height, 1)
gaussian_ids_sorted = torch.arange(0, num_points)
tile_bins = torch.zeros(num_points, 2, dtype=torch.int32)
xys = torch.randn(num_points, 2)
conics = torch.rand(num_points, 2)
colors = torch.rand(num_points, 3)
opacities = torch.rand(num_points)
background = torch.rand(3)
rasterize_forward(tile_bounds, 
		  block, 
		  img_size,
		  gaussian_ids_sorted,
		  tile_bins,
		  xys,
		  conics,
		  colors,
		  opacities,
		  background) 
```
The example code throws an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arl/Projects/gsplat/gsplat/_torch_impl.py", line 574, in rasterize_forward
    final_idx[i, j] = idx
UnboundLocalError: local variable 'idx' referenced before assignment
```

**Comment by liruilong940607** [comment]
Close as the code is now updated to v1.0.0 with different code structure!
