### ISSUE TITLE
OverflowError: Python integer -1 out of bounds for uint64

### ISSUE THREAD

**Issue by rkakash59** [nerfstudio-project/gsplat#231]
I am getting above error when I run:
python simple_trainer.py --data_dir nerf_data/data/garden/ --data_factor 4 --result_dir ./results/garden

**Comment by liruilong940607** [comment]
any more error log and env info you can share?

**Comment by rkakash59** [comment]
@liruilong940607 I pip installed this torch wheel: https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-linux_x86_64.whl#sha256=f6e26492d214edab5b407e903ed3c7b190ac5709330bd72060d1be01b354c198

Then pip installed gsplat from source: pip install git+https://github.com/nerfstudio-project/gsplat.git

Then pip install -r requirements.txt (in examples folder)

error log:
(env_gsplat) :~/Gaussian_splatting/gsplat_studio/gsplat/examples$ python simple_trainer.py --data_dir /nerf_data/data/garden/ --data_factor 4 --result_dir ./results/garden
Traceback (most recent call last):
  File "/home/ard/Gaussian_splatting/gsplat_studio/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/home/ard/Gaussian_splatting/gsplat_studio/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/home/ard/Gaussian_splatting/gsplat_studio/env_gsplat/lib/python3.10/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/home/ard/Gaussian_splatting/gsplat_studio/env_gsplat/lib/python3.10/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/home/ard/Gaussian_splatting/gsplat_studio/env_gsplat/lib/python3.10/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
OverflowError: Python integer -1 out of bounds for uint64

Data folder structure:
![image](https://github.com/nerfstudio-project/gsplat/assets/24909406/08147ecb-708b-49b0-b61b-2e4e080a6bd4)

**Comment by liruilong940607** [comment]
Hi, 

I think it's the latest numpy deprecate the support of conversion of out-of-bound Python integers, which is required in `pycolmap` at [here](https://github.com/rmbrualla/pycolmap/blob/cc7ea4b7301720ac29287dbe450952511b32125e/pycolmap/scene_manager.py#L22C23-L22C36).

We use `numpy==1.26.4` in our development in a Linux environment. Maybe you can try this numpy version? Hopefully it will behave the same way in windows.

**Comment by rkakash59** [comment]
@liruilong940607 Thank you!!

using numpy==1.26.4 solved this.(i was using numpy==2.0.0)
