### ISSUE TITLE
benchmark.sh failed by out of bounds for unit64 error

### ISSUE THREAD

**Issue by MasahiroOgawa** [nerfstudio-project/gsplat#239]
the error message is below
"""
$ bash benchmark.sh 
Running bicycle
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running bonsai
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running counter
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running garden
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running kitchen
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running room
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Running stump
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 8, in <module>
    from pycolmap import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/__init__.py", line 4, in <module>
    from .scene_manager import SceneManager
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 21, in <module>
    class SceneManager:
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/pycolmap/scene_manager.py", line 22, in SceneManager
    INVALID_POINT3D = np.uint64(-1)
                      ^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
"""

**Comment by MasahiroOgawa** [comment]
I created my environment by poetry. my pyproject.toml is as below.
`[tool.poetry]
name = "gsplat-pip"
version = "0.1.0"
description = ""
authors = ["Masahiro Ogawa <masahiro.ogaw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = {version = "^2.3.1+cu121", source = "torch_cu121"}
torchvision = {version = "^0.18.1+cu121", source = "torch_cu121"}
torchaudio = {version = "^2.3.1+cu121", source = "torch_cu121"}
pycolmap = {git = "https://github.com/rmbrualla/pycolmap", rev = "cc7ea4b7301720ac29287dbe450952511b32125e"}
viser = "^0.2.1"
nerfview = "0.0.2"
imageio = {extras = ["ffmpeg"], version = "^2.34.2"}
numpy = "^2.0.0"
scikit-learn = "^1.5.0"
tqdm = "^4.66.4"
torchmetrics = {extras = ["image"], version = "^1.4.0.post0"}
opencv-python = "^4.10.0.84"
tyro = "^0.8.5"
pillow = "^10.3.0"
tensorboard = "^2.17.0"


[[tool.poetry.source]]
name = "torch_cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
`

**Comment by liruilong940607** [comment]
Hi does #231 provides you a solution?

**Comment by MasahiroOgawa** [comment]
Thanks. I will try numpy==1.26.4.

**Comment by MasahiroOgawa** [comment]
Thanks! It seems that it pass this error!

But I got another error; COLMAP directory data/360_v2/bicycle/sparse does not exist.
But This is another error.
I will check other issues and if it is not exist, I will open new issue.

The all error message is here;
> $ bash benchmark.sh 
Running bicycle
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/bicycle/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/bicycle/sparse does not exist.
Running bonsai
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/bonsai/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/bonsai/sparse does not exist.
Running counter
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/counter/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/counter/sparse does not exist.
Running garden
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/garden/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/garden/sparse does not exist.
Running kitchen
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/kitchen/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/kitchen/sparse does not exist.
Running room
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/room/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/room/sparse does not exist.
Running stump
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/stump/sparse does not exist.
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 959, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 939, in main
    runner = Runner(cfg)
             ^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer.py", line 233, in __init__
    self.parser = Parser(
                  ^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/datasets/colmap.py", line 45, in __init__
    assert os.path.exists(
AssertionError: COLMAP directory data/360_v2/stump/sparse does not exist.
=== Eval Stats ===
results/benchmark/bicycle/stats/val*
cat: 'results/benchmark/bicycle/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/bicycle/stats/train*
cat: 'results/benchmark/bicycle/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/bonsai/stats/val*
cat: 'results/benchmark/bonsai/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/bonsai/stats/train*
cat: 'results/benchmark/bonsai/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/counter/stats/val*
cat: 'results/benchmark/counter/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/counter/stats/train*
cat: 'results/benchmark/counter/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/garden/stats/val*
cat: 'results/benchmark/garden/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/garden/stats/train*
cat: 'results/benchmark/garden/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/kitchen/stats/val*
cat: 'results/benchmark/kitchen/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/kitchen/stats/train*
cat: 'results/benchmark/kitchen/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/room/stats/val*
cat: 'results/benchmark/room/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/room/stats/train*
cat: 'results/benchmark/room/stats/train*': No such file or directory

=== Eval Stats ===
results/benchmark/stump/stats/val*
cat: 'results/benchmark/stump/stats/val*': No such file or directory

=== Train Stats ===
results/benchmark/stump/stats/train*
cat: 'results/benchmark/stump/stats/train*': No such file or directory

**Comment by liruilong940607** [comment]
do you have the mipnerf360 data in the folder `examples/data/360_v2/{garden, bicycle, ...}`? Our script assumes such file path structure

**Comment by MasahiroOgawa** [comment]
oh I didn't know that. OK I will download it. where does it exist?

**Comment by liruilong940607** [comment]
See this #223

**Comment by MasahiroOgawa** [comment]
Thank you very much! I will download it. 
After downloading and confirming it works, I will close this issue.

**Comment by MasahiroOgawa** [comment]
Thank you, today I finally download the data.
But I got another error; https://github.com/nerfstudio-project/gsplat/issues/249
But anyway, this is another error, and the title error was fixed by Liruilong's support.
Thank you.
