### ISSUE TITLE
Failed install the gsplat

### ISSUE THREAD

**Issue by mingqiJ** [nerfstudio-project/gsplat#264]
When I use the `pip install git+https://github.com/nerfstudio-project/gsplat.git` to install the gsplat. It takes error:

```
g++: error: /tmp/pip-req-build-r6lwswgw/build/temp.linux-x86_64-cpython-38/gsplat/cuda_legacy/csrc/backward.o: No such file or directory
      g++: error: /tmp/pip-req-build-r6lwswgw/build/temp.linux-x86_64-cpython-38/gsplat/cuda_legacy/csrc/bindings.o: No such file or directory
      g++: error: /tmp/pip-req-build-r6lwswgw/build/temp.linux-x86_64-cpython-38/gsplat/cuda_legacy/csrc/ext.o: No such file or directory
      g++: error: /tmp/pip-req-build-r6lwswgw/build/temp.linux-x86_64-cpython-38/gsplat/cuda_legacy/csrc/forward.o: No such file or directory
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gsplat
  Running setup.py clean for gsplat
Failed to build gsplat
ERROR: Could not build wheels for gsplat, which is required to install pyproject.toml-based projects
```

Is there any solution to fix this?
My nvcc is 11.8. And gcc/g++ is 10.5.0

**Comment by mingqiJ** [comment]
And if I didn't do anything, it will take this error:
```
Traceback (most recent call last):
      File "/home/anaconda3/envs/gsplat118/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
        subprocess.run(
      File "/home/anaconda3/envs/gsplat118/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '10']' returned non-zero exit status 1.
```

But when I use `ninja --version`, it said I already have:
`1.11.1.git.kitware.jobserver-1`

Do you know why it is?

**Comment by mingqiJ** [comment]
Does anyone know why it takes error when building wheel?

**Comment by Atticuszz** [comment]
how about git cloned ，and then pip intall .，it works for me.
but the  version was a bit wired for me recently,cause it almost took me 32G ram to comple

**Comment by SnowdenLee** [comment]
Hi @mingqiJ did you solve this issue? I have met the same one
Thank you

**Comment by zombie-island** [comment]
I  fix this error by updating my g++ ‘s version from 7.5 to 11.2.0.Maybe the gcc's version is right,but g++'s version is not set correctly.

**Comment by scott198510** [comment]
@SnowdenLee @mingqiJ 
Yes, I encountered the same issue during installation, but I don't have the previous gcc version,

vim /home/users/xu.li/miniconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py
# line 1858: command = ['ninja', '-v']  ->  command = ['ninja', '--version']
# line 1636: subprocess.check_output('ninja --version'.split())  ->  subprocess.check_output('ninja -v'.split())

**Comment by Shanzhaguoo** [comment]
I fixed the error by setting "use_ninja=False" in the setup.py:
def get_ext():
  from torch.utils.cpp_extension import BuildExtension
  return BuildExtension.with_options(no_python_abi_suffix=True, use_ninja=False)
