### ISSUE TITLE
Errors of rasterize

### ISSUE THREAD

**Issue by mingqiJ** [nerfstudio-project/gsplat#266]
I always failed to install the gsplat.
So I transfer other people's conda environment to run the gsplat, but it takes this error:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    colors, alphas, meta = rasterization(
  File "/home/anaconda3/envs/gs/lib/python3.8/site-packages/gsplat/rendering.py", line 360, in rasterization
    render_colors, render_alphas = rasterize_to_pixels(
  File "/home/anaconda3/envs/gs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 481, in rasterize_to_pixels
    render_colors, render_alphas = _RasterizeToPixels.apply(
  File "/home/anaconda3/envs/gs/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anaconda3/envs/gs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 824, in forward
    render_colors, render_alphas, last_ids = _make_lazy_cuda_func(
  File "/home/anaconda3/envs/gs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 12, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: Failed to set maximum shared memory size (requested 7168 bytes), try lowering tile_size.
```

Could you tell me how to correct install the gsplat?

**Comment by Atticuszz** [comment]
try lowering tile_size

**Comment by vasile-v1** [comment]
> try lowering tile_size

How to setting， where？

**Comment by DabblerGISer** [comment]
Hi, have you solved this problem? kindly ask for the solution, thank you very much.

**Comment by Atticuszz** [comment]
[here is the docs](https://docs.gsplat.studio/main/apis/rasterization.html),which defines the interface 

use ctrl +f in browser to find which parameters you wanna have a look

**Comment by DabblerGISer** [comment]
> [here is the docs](https://docs.gsplat.studio/main/apis/rasterization.html),which defines the function `rasterization`
> 
> use ctrl +f in browser to find which parameters you wanna have a look
> 
> hope it would help :) @vasile-v1 @DabblerGISer

Thank you for your reply! 
I'm not solving configuration locally. It runs perfectly on my conda env. But now I'm trying to pack my project to use on another computer, and it turns out that the rasterization part can't reference the cuda code correctly. Im looking for a good way to solve this.

**Comment by ge95pep** [comment]
Hi, @DabblerGISer @mingqiJ 
Did you solve this problem? I encountered it as well. I 've tried a lot of diffenrent GPUs, the code runs fine on some GPUs (like RTX 4050, 4070), and some get error like yours (RTX 3070...). I tried lower tile_size, but it didn't work.

**Comment by axbycc-mark** [comment]
I recently encountered this problem on the RTX A6000, Ubuntu 22.04.5 LTS, Python 3.11, torch 2.4.0+cu124, Cuda 12.5. This error message was a red herring for me, possibly due to gsplat swallowing a lower level error from the cuda runtime.

When you call rasterize() the first time after installing, gsplat will try to compile itself with whatever nvcc it finds on your system and for whatever architectures are detected. For some reason, it was not compiled with the correct architecture for my GPU. I fixed it using the following method.

1. Remove any cached versions gsplat previously produced (on my machine these were located at ~/.cache/torch_extensions/py311_cu124/gsplat_cuda).
2. Make a .py file where you call gsplat.render, but at the top of the file, put `os.environ["TORCH_CUDA_ARCH_LIST"] = "8.0 8.6+PTX 9.0+PTX` (you need to also `import os` before that of course)
3. Run the .py file from step 2. 

This will trigger gsplat to recompile the cuda binaries for the architectures mentioned in the list from step 2. I'm not sure what architectures are needed for which GPUs, but this worked for my RTX A6000.

**Comment by ge95pep** [comment]
@axbycc-mark Thanks a lot ! I solved this problem last month with the same solution as you mentioned. Just type `export TORCH_CUDA_ARCH_LIST="8.6 8.0 7.5"` (add any computation capability as you want) in terminal before reinstalling gsplat. I didn't try "+PTX", but it works for me right now, and it runs smoothly on many different types of GPUs. 
(For someone might need this : gsplat may not support GPUs with computation capability lower than 7.0,  just like the official rasterizer.)

**Comment by liruilong940607** [comment]
nice seems this has been resolved. so closing

**Comment by liulisixin** [comment]
I ran the 4-GPU training script and encountered the following error:
RuntimeError: Failed to set maximum shared memory size (requested 7168 bytes), try lowering tile_size.

However, the script works after I removed the --packed flag.

```
    # train and eval at the last step (30000)
    # 4 GPUs is effectively 4x batch size so we scale down the steps by 4x as well.
    # "--packed" reduces the data transfer between GPUs, which leads to faster training. 
    CUDA_VISIBLE_DEVICES=0,1,2,3 python simple_trainer.py default --eval_steps 30000 --disable_viewer --data_factor $DATA_FACTOR \
        --steps_scaler 0.25 --packed \
        --data_dir data/360_v2/$SCENE/ \
        --result_dir $RESULT_DIR/$SCENE/
