### ISSUE TITLE
simple_trainer_mcmc.py crash

### ISSUE THREAD

**Issue by MasahiroOgawa** [nerfstudio-project/gsplat#280]
When I run example/simple_trainer_mcmc.py, It crashes the browser.
The whole error message is below.

## Whole error message
>poetry run python simple_trainer_mcmc.py --data_factor 8 --global_scale 0.2
Warning: image_path not found for reconstruction
[Parser] 185 images, taken by 1 cameras.
Scene scale: 0.24530526131617825
Model initialized. Number of GS: 138766
╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:8080   │
│   Websocket │ ws://0.0.0.0:8080     │
│             ╵                       │
╰─────────────────────────────────────╯
  0%|                                                                                                                                       | 0/30000 [00:00<?, ?it/s]/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
  0%|                                                                                                                                       | 0/30000 [00:37<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/cuda/_backend.py", line 46, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer_mcmc.py", line 830, in <module>
    main(cfg)
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer_mcmc.py", line 820, in main
    runner.train()
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer_mcmc.py", line 388, in train
    renders, alphas, info = self.rasterize_splats(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer_mcmc.py", line 296, in rasterize_splats
    render_colors, render_alphas, info = rasterization(
                                         ^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/rendering.py", line 218, in rasterization
    proj_results = fully_fused_projection(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/cuda/_wrapper.py", line 260, in fully_fused_projection
    return _FullyFusedProjection.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/cuda/_wrapper.py", line 712, in forward
    radii, means2d, depths, conics, compensations = _make_lazy_cuda_func(
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/cuda/_wrapper.py", line 10, in call_cuda
    from ._backend import _C
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/gsplat/cuda/_backend.py", line 77, in <module>
    _C = load(
         ^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/mnt/home/mas/anaconda3/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/mas/anaconda3/lib/python3.11/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by Atticuszz** [comment]
i encounter this as well as poetry add gsplat，bug is `can not import c`,which means download package from pip index，so I tried to install it as local submodule, needing  compile and cuda toolkit is necessary. and gsplat  needs `torch` as depency , poetry  add torch is my first way of installing torch,seems loss some package and is quiet different  from official commands from conda and pip, after switching  to conda for installing total torch and accompanying with cuda toolkits ,compile gsplat locally  for conda,then it works all ok

**Comment by MasahiroOgawa** [comment]
Thanks @Atticuszz , then I will use venv or docker instead of poetry.

**Comment by Atticuszz** [comment]
> Thanks @Atticuszz , then I will use venv or docker instead of poetry.

or just after running poetry shell,[follow official pip  commands](https://pytorch.org/get-started/locally/)
