### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes (error running example data sets on Windows)

### ISSUE THREAD

**Issue by MrDieAlot** [nerfstudio-project/gsplat#458]
Hi, finally managed to install Gsplat on my Win 11 (RTX3090) machine without issues using CUDA 12.4, but am running into problems running the simple_trainer.py file. 
Am getting the following error when trying to run the example data sets:

(gsplat) C:\gsplat>python C:\gsplat\examples\simple_trainer.py default --data_dir data\360_v2\garden\
Warning: image_path not found for reconstruction
Traceback (most recent call last):
  File "C:\gsplat\examples\simple_trainer.py", line 1094, in <module>
    cli(main, cfg, verbose=True)
  File "C:\Users\s_m_d\miniforge3\envs\gsplat\lib\site-packages\gsplat\distributed.py", line 360, in cli
    return _distributed_worker(0, 1, fn=fn, args=args)
  File "C:\Users\s_m_d\miniforge3\envs\gsplat\lib\site-packages\gsplat\distributed.py", line 295, in _distributed_worker
    fn(local_rank, world_rank, world_size, args)
  File "C:\gsplat\examples\simple_trainer.py", line 1023, in main
    runner = Runner(local_rank, world_rank, world_size, cfg)
  File "C:\gsplat\examples\simple_trainer.py", line 302, in __init__
    self.parser = Parser(
  File "C:\gsplat\examples\datasets\colmap.py", line 52, in __init__
    manager.load_cameras()
  File "C:\Users\s_m_d\miniforge3\envs\gsplat\lib\site-packages\pycolmap\scene_manager.py", line 90, in load_cameras
    self._load_cameras_bin(input_file)
  File "C:\Users\s_m_d\miniforge3\envs\gsplat\lib\site-packages\pycolmap\scene_manager.py", line 102, in _load_cameras_bin
    num_cameras = struct.unpack('L', f.read(8))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by KevinXu02** [comment]
This PR might help. (https://github.com/rmbrualla/pycolmap/pull/2）

**Comment by MrDieAlot** [comment]
That worked, thanks!

**Comment by yanqswhu** [comment]
> This PR might help. ([https://github.com/rmbrualla/pycolmap/pull/2）](https://github.com/rmbrualla/pycolmap/pull/2%EF%BC%89)

Works for me! Thanks!

**Comment by supertan0204** [comment]
Can anyone tell me what happened? It seems like the link is broken... 

> This PR might help. ([https://github.com/rmbrualla/pycolmap/pull/2）](https://github.com/rmbrualla/pycolmap/pull/2%EF%BC%89)

**Comment by liruilong940607** [comment]
This is the link: https://github.com/rmbrualla/pycolmap/pull/2

Closing as it is not the issue of this repo and has been resolved.
