### ISSUE TITLE
Error when running simple_trainer.py

### ISSUE THREAD

**Issue by Limonka11** [nerfstudio-project/gsplat#461]
I get the following error when I try to run the example training script from a google colab notebook.
```
/content/gsplat
2024-10-22 05:04:33.861470: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-22 05:04:33.881873: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-22 05:04:33.887986: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-22 05:04:33.903240: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-22 05:04:35.573968: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Warning: image_path not found for reconstruction
[Parser] 185 images, taken by 1 cameras.
Scene scale: 1.2265263065808907
Model initialized. Number of GS: 138766
/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/image/lpips.py:325: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:8081/   │
│   Websocket │ ws://0.0.0.0:8081     │
│             ╵                       │
╰─────────────────────────────────────╯
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
  0% 0/30000 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: 
TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
(    ● ) gsplat: Setting up CUDA with MAX_JOBS=10 (This may take a few minutes the first time)
  0% 0/30000 [00:20<?, ?it/s]
Traceback (most recent call last):
  File "/content/gsplat/gsplat/cuda/_backend.py", line 83, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/content/gsplat/gsplat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '10']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/gsplat/simple_trainer.py", line 1094, in <module>
    cli(main, cfg, verbose=True)
  File "/content/gsplat/gsplat/distributed.py", line 360, in cli
    return _distributed_worker(0, 1, fn=fn, args=args)
  File "/content/gsplat/gsplat/distributed.py", line 295, in _distributed_worker
    fn(local_rank, world_rank, world_size, args)
  File "/content/gsplat/simple_trainer.py", line 1039, in main
    runner.train()
  File "/content/gsplat/simple_trainer.py", line 593, in train
    renders, alphas, info = self.rasterize_splats(
  File "/content/gsplat/simple_trainer.py", line 473, in rasterize_splats
    render_colors, render_alphas, info = rasterization(
  File "/content/gsplat/gsplat/rendering.py", line 297, in rasterization
    proj_results = fully_fused_projection(
  File "/content/gsplat/gsplat/cuda/_wrapper.py", line 324, in fully_fused_projection
    return _FullyFusedProjection.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/content/gsplat/gsplat/cuda/_wrapper.py", line 796, in forward
    camera_model_type = _make_lazy_cuda_obj(
  File "/content/gsplat/gsplat/cuda/_wrapper.py", line 39, in _make_lazy_cuda_obj
    from ._backend import _C
  File "/content/gsplat/gsplat/cuda/_backend.py", line 130, in <module>
    _C = load_extension(
  File "/content/gsplat/gsplat/cuda/_backend.py", line 42, in load_extension
    return load(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gsplat_cuda': [1/27] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output rasterize_to_pixels_fwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/rasterize_to_pixels_fwd.cu -o rasterize_to_pixels_fwd.cuda.o 
FAILED: rasterize_to_pixels_fwd.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output rasterize_to_pixels_fwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/rasterize_to_pixels_fwd.cu -o rasterize_to_pixels_fwd.cuda.o 
In file included from /content/gsplat/gsplat/cuda/csrc/helpers.cuh:4,
                 from /content/gsplat/gsplat/cuda/csrc/rasterize_to_pixels_fwd.cu:2:
/content/gsplat/gsplat/cuda/csrc/types.cuh:8:10: fatal error: glm/glm.hpp: No such file or directory
    8 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
[2/27] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fully_fused_projection_packed_fwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_fwd.cu -o fully_fused_projection_packed_fwd.cuda.o 
FAILED: fully_fused_projection_packed_fwd.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fully_fused_projection_packed_fwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_fwd.cu -o fully_fused_projection_packed_fwd.cuda.o 
In file included from /content/gsplat/gsplat/cuda/csrc/helpers.cuh:4,
                 from /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_fwd.cu:2:
/content/gsplat/gsplat/cuda/csrc/types.cuh:8:10: fatal error: glm/glm.hpp: No such file or directory
    8 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
[3/27] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output isect_tiles.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/isect_tiles.cu -o isect_tiles.cuda.o 
FAILED: isect_tiles.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output isect_tiles.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/isect_tiles.cu -o isect_tiles.cuda.o 
In file included from /content/gsplat/gsplat/cuda/csrc/helpers.cuh:4,
                 from /content/gsplat/gsplat/cuda/csrc/isect_tiles.cu:2:
/content/gsplat/gsplat/cuda/csrc/types.cuh:8:10: fatal error: glm/glm.hpp: No such file or directory
    8 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
[4/27] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fully_fused_projection_packed_2dgs_bwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_2dgs_bwd.cu -o fully_fused_projection_packed_2dgs_bwd.cuda.o 
FAILED: fully_fused_projection_packed_2dgs_bwd.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fully_fused_projection_packed_2dgs_bwd.cuda.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/content/gsplat/gsplat/cuda/csrc -I/content/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -c /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_2dgs_bwd.cu -o fully_fused_projection_packed_2dgs_bwd.cuda.o 
In file included from /content/gsplat/gsplat/cuda/csrc/helpers.cuh:4,
                 from /content/gsplat/gsplat/cuda/csrc/fully_fused_projection_packed_2dgs_bwd.cu:2:
/content/gsplat/gsplat/cuda/csrc/types.cuh:8:10: fatal error: glm/glm.hpp: No such file or directory
    8 | #include <glm/glm.hpp>
```

I install the gsplat project like this:
```
!pip install git+https://github.com/nerfstudio-project/gsplat.git
!pip install -r gsplat/examples/requirements.txt
```

and download the data:
```
!python gsplat/examples/datasets/download_dataset.py
```

However, when I try to run  the training script like this:
```
%cd /content/gsplat
!CUDA_VISIBLE_DEVICES=0 python simple_trainer.py default \
    --data_dir ../data/360_v2/garden/ --data_factor 4 \
    --result_dir ./results/garden
```

I get the error. Could you please help me with that

**Comment by maturk** [comment]
Looks like the submodules are not correctly cloned?

Does `git clone --recurse-submodules https://github.com/nerfstudio-project/gsplat/` fix it? Or you can cd to your gsplat clone and do `git submodule update --init --recursive`

**Comment by Limonka11** [comment]
It seems like this fixed it! Thanks!

**Comment by Guochh01** [comment]
> Looks like the submodules are not correctly cloned? glm is a submodule that should exist in the `gsplat/gsplat/cuda/csrc/third_party` folder.
> 
> Does `git clone --recurse-submodules https://github.com/nerfstudio-project/gsplat/` fix it? Or you can cd to your gsplat clone and do `git submodule update --init --recursive`


I encountered a similar issue with gsplat v1.5.3. Even after running `sudo apt install libglm-dev`, I was unable to compile and generate `gsplat_cuda.so`. 
```bash
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/xxx/lib/python3.10/site-packages/gsplat/cuda/_backend.py", line 46, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/home/xxx/miniconda3/envs/xxx/lib/python3.10/site-packages/gsplat/__init__.py)
...
ImportError: /home/xxx/.cache/torch_extensions/py310_cu118/gsplat_cuda/gsplat_cuda.so: cannot open shared object file: No such file or directory
```

I eventually found that the problem was caused by failing to clone the third-party GLM library.

In general, running the following command resolves the issue:
```bash
cd gsplat
git submodule update --init --recursive
pip unintall gsplat
pip install .
```
