### ISSUE TITLE
New COLMAP dataset does not work

### ISSUE THREAD

**Issue by chgara** [nerfstudio-project/gsplat#475]
I have the following problem when running a new created dataset using colmap.

When using gsplat version 1.0.0 with this dataset an error is thrown of cv2, but when using this dataset in a new gsplat version it does not throw any error but it does not reconstruct the scene, only puts the gaussians in random places.

When using an old dataset created from this same images it works perfectly, neither the older version gives an error and the new one does reconstruct the scene.

Here it is the error of the old gsplat with the new dataset:

```
[Parser] 891 images, taken by 1 cameras.
Warning: COLMAP Camera is not PINHOLE. Images have distortion.
Traceback (most recent call last):
  File "simple_trainer.py", line 1024, in <module>
    main(cfg)
  File "simple_trainer.py", line 1002, in main
    runner = Runner(cfg)
  File "simple_trainer.py", line 254, in __init__
    self.parser = Parser(
  File "/home/phobos/Documents/sala-cero/tools/gsplat/examples/datasets/colmap.py", line 209, in __init__
    K_undist, roi_undist = cv2.getOptimalNewCameraMatrix(
cv2.error: OpenCV(4.8.0) /io/opencv/modules/calib3d/src/undistort.dispatch.cpp:411: error: (-215:Assertion failed) CV_IS_MAT(_distCoeffs) && (_distCoeffs->rows == 1 || _distCoeffs->cols == 1) && (_distCoeffs->rows*_distCoeffs->cols == 4 || _distCoeffs->rows*_distCoeffs->cols == 5 || _distCoeffs->rows*_distCoeffs->cols == 8 || _distCoeffs->rows*_distCoeffs->cols == 12 || _distCoeffs->rows*_distCoeffs->cols == 14) in function 'cvUndistortPointsInternal'655.53282660901652 -0.067447483961878094 0.094515059343597857 -0.001065642607859337 -0.0007505122237943246

```

And this is a part of the cameras.txt of the new created dataset (only one)

```
# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 SIMPLE_RADIAL 2000 1335 1911.6164006907477 1000 667.5 -0.034307169250350558
```
And this the old one cameras.txt:

```
# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 OPENCV 2000 1335 1917.5572290805967 1918.150934853863 994.78688294128722 655.53282660901652 -0.067447483961878094 0.094515059343597857 -0.001065642607859337 -0.0007505122237943246

```

I dont mind about the error on the old gsplat version, but i want to know why the new created datasets does not work in the reconstruction in the new one and the old one does, and for me seems to be related, as the old dataset does not have any problems in any version but the new one generated does have the older problem and the new one does not reconstruct.

**Comment by chgara** [comment]
I should say that in the colmap GUI the two datasets look identically, so seems correct
