### ISSUE TITLE
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gsplat)

### ISSUE THREAD

**Issue by pattise** [nerfstudio-project/gsplat#481]
hello
I'm getting this error when trying to install gsplat.

  
          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'gsplat.compression' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'gsplat.compression' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'gsplat.compression' to be distributed and are
          already explicitly excluding 'gsplat.compression' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  /home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/command/build_py.py:220: _Warning: Package 'gsplat.optimizers' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'gsplat.optimizers' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'gsplat.optimizers' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'gsplat.optimizers' to be distributed and are
          already explicitly excluding 'gsplat.optimizers' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  /home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/command/build_py.py:220: _Warning: Package 'gsplat.strategy' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'gsplat.strategy' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'gsplat.strategy' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'gsplat.strategy' to be distributed and are
          already explicitly excluding 'gsplat.strategy' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/lyx/shape-of-motion/gsplat/setup.py", line 107, in <module>
      setup(
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
      return run_commands(dist)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
      dist.run_commands()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
      self.run_command(cmd)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
      super().run_command(command)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 410, in run
      self.run_command("build")
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
      super().run_command(command)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
      super().run_command(command)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
      _build_ext.run(self)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
      self.build_extensions()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
      build_ext.build_extensions(self)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
      self._build_extensions_serial()
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
      objects = self.compiler.compile(
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
      _write_ninja_file_and_compile_objects(
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
      _run_ninja_build(
    File "/home/lyx/anaconda3/envs/som/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/lyx/anaconda3/envs/som/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/lyx/shape-of-motion/gsplat/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-_92ht4t_
  cwd: /home/lyx/shape-of-motion/gsplat/
  Building wheel for gsplat (setup.py) ... error
  ERROR: Failed building wheel for gsplat
  Running setup.py clean for gsplat
  Running command python setup.py clean
  Setting MAX_JOBS to 10
  running clean
  removing 'build/temp.linux-x86_64-cpython-310' (and everything under it)
  removing 'build/lib.linux-x86_64-cpython-310' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.10' does not exist -- can't clean it
  removing 'build'
  Unsetting MAX_JOBS
Failed to build gsplat
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gsplat)

Hope to get some help from you, thanks a million!

**Comment by Fabulani** [comment]
In my case, I fixed the issue by increasing WSL memory to 8GB and (more importantly) installing `libglm-dev`:

```
apt-get install libglm-dev
```

This allowed `gsplat` to properly compile all the CUDA stuff. The actual error can be spotted with `pip install . --verbose`, in my case I was missing some C++ GLM headers (ubuntu22.04 base image).

**Comment by HuangZhengyang-2004** [comment]
> In my case, I fixed the issue by increasing WSL memory to 8GB and (more importantly) installing `libglm-dev`:
> 
> ```
> apt-get install libglm-dev
> ```
> 
> This allowed `gsplat` to properly compile all the CUDA stuff. The actual error can be spotted with `pip install . --verbose`, in my case I was missing some C++ GLM headers (ubuntu22.04 base image).

How should I handle this situation on a Linux system?

**Comment by Shanzhaguoo** [comment]
> > In my case, I fixed the issue by increasing WSL memory to 8GB and (more importantly) installing `libglm-dev`:
> > ```
> > apt-get install libglm-dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This allowed `gsplat` to properly compile all the CUDA stuff. The actual error can be spotted with `pip install . --verbose`, in my case I was missing some C++ GLM headers (ubuntu22.04 base image).
> 
> How should I handle this situation on a Linux system?

Did you solve the problem? I met the same problem on linux system. Btw, is it possible to install both gsplat and the original diff-gaussian-rasterization libraries simultaneously in the same environment?

**Comment by Fabulani** [comment]
I ended up using a different strategy to install gsplat in a container. You can check out my Dockerfile [here](https://github.com/Fabulani/tasks-for-splats/blob/main/gsplat/docker/Dockerfile). Basically, commit ae729d3 fixed a compilation error that had been bugging me for a long time. This is the install part I did (along with installing libglm-dev):

```dockerfile
# Clone, install, and compile gsplat and its CUDA scripts
# Note: commit must be later than ae729d3 - this fixes a cuda compilation error!
ARG GIT_COMMIT_ID=e86f392
RUN git clone https://github.com/nerfstudio-project/gsplat.git --recursive && \
    cd gsplat && \
    git checkout ${GIT_COMMIT_ID}
RUN pip install --no-cache-dir git+https://github.com/nerfstudio-project/gsplat.git@${GIT_COMMIT_ID}
```

I clone the repo so I can use its code, just the pip install should be enough if you don't need that :)
