### ISSUE TITLE
OOM issue and blank validation results using mcmc strategy

### ISSUE THREAD

**Issue by LaFeuilleMorte** [nerfstudio-project/gsplat#487]
Hi, I've tried mcmc strategy on smaller subset (about 542 images, 150, 000 initial point cloud), which works quite good. But when I'm using the whole dataset (about 973 images, 360, 000 initial point cloud). After about 6400 steps. It will raise cuda oom issue. And when I was trying to lower the cam_max to 500_000 for each GPU, the validation results would be blank images. I tested with the default strategy and it works well.

2024-11-12 14:31:14.832 | Step 600: Relocated 6711 GSs. |  
-- | -- | --
  |   | 2024-11-12 14:31:14.832 | Step 600: Added 3058 GSs. Now having 64232 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 700: Relocated 6183 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 700: Added 3211 GSs. Now having 67443 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 800: Relocated 7833 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 800: Added 3372 GSs. Now having 70815 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 900: Relocated 9543 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 900: Added 3540 GSs. Now having 74355 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1000: Relocated 10506 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1000: Added 3717 GSs. Now having 78072 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1100: Relocated 11628 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1100: Added 3903 GSs. Now having 81975 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1200: Relocated 12843 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1200: Added 4098 GSs. Now having 86073 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1300: Relocated 14028 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1300: Added 4303 GSs. Now having 90376 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1400: Relocated 14801 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1400: Added 4518 GSs. Now having 94894 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1500: Relocated 16015 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1500: Added 4744 GSs. Now having 99638 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1600: Relocated 17936 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1600: Added 4981 GSs. Now having 104619 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1700: Relocated 18905 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1700: Added 5230 GSs. Now having 109849 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1800: Relocated 19534 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1800: Added 5492 GSs. Now having 115341 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1900: Relocated 21572 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 1900: Added 5767 GSs. Now having 121108 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2000: Relocated 23384 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2000: Added 6055 GSs. Now having 127163 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2100: Relocated 24955 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2100: Added 6358 GSs. Now having 133521 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2200: Relocated 26519 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2200: Added 6676 GSs. Now having 140197 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2300: Relocated 28950 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2300: Added 7009 GSs. Now having 147206 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2400: Relocated 30953 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2400: Added 7360 GSs. Now having 154566 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2500: Relocated 33083 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2500: Added 7728 GSs. Now having 162294 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2600: Relocated 35289 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2600: Added 8114 GSs. Now having 170408 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2700: Relocated 38176 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2700: Added 8520 GSs. Now having 178928 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2800: Relocated 40111 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2800: Added 8946 GSs. Now having 187874 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2900: Relocated 42220 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 2900: Added 9393 GSs. Now having 197267 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3000: Relocated 46251 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3000: Added 9863 GSs. Now having 207130 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3100: Relocated 49781 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3100: Added 10356 GSs. Now having 217486 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3200: Relocated 52763 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3200: Added 10874 GSs. Now having 228360 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3300: Relocated 57216 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3300: Added 11418 GSs. Now having 239778 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3400: Relocated 60003 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3400: Added 11988 GSs. Now having 251766 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3500: Relocated 63374 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3500: Added 12588 GSs. Now having 264354 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3600: Relocated 68636 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3600: Added 13217 GSs. Now having 277571 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3700: Relocated 75445 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3700: Added 13878 GSs. Now having 291449 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3800: Relocated 78193 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3800: Added 14572 GSs. Now having 306021 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3900: Relocated 83798 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 3900: Added 15301 GSs. Now having 321322 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4000: Relocated 91040 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4000: Added 16066 GSs. Now having 337388 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4100: Relocated 103474 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4100: Added 16869 GSs. Now having 354257 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4200: Relocated 111334 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4200: Added 17712 GSs. Now having 371969 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4300: Relocated 115157 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4300: Added 18598 GSs. Now having 390567 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4400: Relocated 123100 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4400: Added 19528 GSs. Now having 410095 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4500: Relocated 134108 GSs. |  
  |   | 2024-11-12 14:31:14.832 | Step 4500: Added 20504 GSs. Now having 430599 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4600: Relocated 139592 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4600: Added 21529 GSs. Now having 452128 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4700: Relocated 152439 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4700: Added 22606 GSs. Now having 474734 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4800: Relocated 159568 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4800: Added 23736 GSs. Now having 498470 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4900: Relocated 165947 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 4900: Added 24923 GSs. Now having 523393 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5000: Relocated 185695 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5000: Added 26169 GSs. Now having 549562 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5100: Relocated 197854 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5100: Added 27478 GSs. Now having 577040 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5200: Relocated 207853 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5200: Added 28852 GSs. Now having 605892 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5300: Relocated 223650 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5300: Added 30294 GSs. Now having 636186 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5400: Relocated 238484 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5400: Added 31809 GSs. Now having 667995 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5500: Relocated 257246 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5500: Added 33399 GSs. Now having 701394 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5600: Relocated 287843 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5600: Added 35069 GSs. Now having 736463 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5700: Relocated 323731 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5700: Added 36823 GSs. Now having 773286 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5800: Relocated 378302 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5800: Added 38664 GSs. Now having 811950 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5900: Relocated 488741 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 5900: Added 40597 GSs. Now having 852547 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6000: Relocated 627827 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6000: Added 42627 GSs. Now having 895174 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6100: Relocated 828458 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6100: Added 44758 GSs. Now having 939932 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6200: Relocated 934401 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6200: Added 46996 GSs. Now having 986928 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6300: Relocated 984383 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6300: Added 13072 GSs. Now having 1000000 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6400: Relocated 995335 GSs. |  
  |   | 2024-11-12 14:31:14.833 | Step 6400: Added 0 GSs. Now having 1000000 GSs. |  
  |   | 2024-11-12 14:31:18.561 | Traceback (most recent call last): |  
  |   | 2024-11-12 14:31:18.561 | File "/aistudio/workspace/aigc/wangqihang013/aigc3d/repos/neural_rendering/high_quality/gsplat/examples/simple_trainer.py", line 1076, in <module> |  
  |   | 2024-11-12 14:31:18.575 | cli(main, cfg, verbose=True) |  
  |   | 2024-11-12 14:31:18.575 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/gsplat/distributed.py", line 344, in cli |  
  |   | 2024-11-12 14:31:18.579 | process_context.join() |  
  |   | 2024-11-12 14:31:18.579 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join |  
  |   | 2024-11-12 14:31:18.580 | raise ProcessRaisedException(msg, error_index, failed_process.pid) |  
  |   | 2024-11-12 14:31:18.580 | torch.multiprocessing.spawn.ProcessRaisedException: |  
  |   | 2024-11-12 14:31:18.580 |   |  
  |   | 2024-11-12 14:31:18.580 | -- Process 0 terminated with the following error: |  
  |   | 2024-11-12 14:31:18.580 | Traceback (most recent call last): |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap |  
  |   | 2024-11-12 14:31:18.580 | fn(i, *args) |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/gsplat/distributed.py", line 295, in _distributed_worker |  
  |   | 2024-11-12 14:31:18.580 | fn(local_rank, world_rank, world_size, args) |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/aigc/wangqihang013/aigc3d/repos/neural_rendering/high_quality/gsplat/examples/simple_trainer.py", line 1021, in main |  
  |   | 2024-11-12 14:31:18.580 | runner.train() |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/aigc/wangqihang013/aigc3d/repos/neural_rendering/high_quality/gsplat/examples/simple_trainer.py", line 589, in train |  
  |   | 2024-11-12 14:31:18.580 | renders, alphas, info = self.rasterize_splats( |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/aigc/wangqihang013/aigc3d/repos/neural_rendering/high_quality/gsplat/examples/simple_trainer.py", line 469, in rasterize_splats |  
  |   | 2024-11-12 14:31:18.580 | render_colors, render_alphas, info = rasterization( |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/gsplat/rendering.py", line 497, in rasterization |  
  |   | 2024-11-12 14:31:18.580 | tiles_per_gauss, isect_ids, flatten_ids = isect_tiles( |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context |  
  |   | 2024-11-12 14:31:18.580 | return func(*args, **kwargs) |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/gsplat/cuda/_wrapper.py", line 382, in isect_tiles |  
  |   | 2024-11-12 14:31:18.580 | tiles_per_gauss, isect_ids, flatten_ids = _make_lazy_cuda_func("isect_tiles")( |  
  |   | 2024-11-12 14:31:18.580 | File "/aistudio/workspace/system-default/envs/gsplat/lib/python3.10/site-packages/gsplat/cuda/_wrapper.py", line 14, in call_cuda |  
  |   | 2024-11-12 14:31:18.580 | return getattr(_C, name)(*args, **kwargs) |  
  |   | 2024-11-12 14:31:18.580 | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.24 GiB. GPU 0 has a total capacty of 39.42 GiB of which 3.14 GiB is free. Process 126936 has 36.29 GiB memory in use. Of the allocated memory 30.47 GiB is allocated by PyTorch, and 2.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by LaFeuilleMorte** [comment]
Alright， I've known why this could happen. Because my dataset was twice larger than the previous one. And there are many noises in my point cloud. Consequently, the mcmc strategy under current configs will produce very large scale gaussians which prevent the gaussians to fit the scene. And according to this issue:

https://github.com/nerfstudio-project/gsplat/issues/464#issue-2608844974

The large scales gaussian will cause the above error in function "isect_tiles"

So I use a larger scale_reg (scale_reg=0.05). And the problem seemed to disappear. But I'm not sure if I choose the optimum scale_reg cofficient.

**Comment by deivse** [comment]
Just a note, surprisingly, I saw better results with lowering opacity regularization rather than increasing scale regularization. With increased scale reg, I still saw this happen on some scenes in scannet++ `nvs_eval_set`. However, using a much lower opacity regularization or disabling it (I settled on `0.0005`), somehow prevented the issue, and produced slightly higher metrics on scenes where the default config did finish.

**Comment by deivse** [comment]
However, this is definitely something that seems possible to address in gsplat by sacrificing rendering quality in extreme cases at the cost of not crashing, e.g. by limiting the total length of the per-tile gaussian list or something like that. I might tackle the implementation at some point if there's interest.
