### ISSUE TITLE
can't install example requirements, because of nvcc pytorch version mismatch when building ssim dependency

### ISSUE THREAD

**Issue by felixniemeyer** [nerfstudio-project/gsplat#524]
after cloning the repo and creating a venv i execute: 
```
pip install torch torchvision torchaudio 
pip install gsplat
cd examples
pip install -r requirements.txt
```

And get this error: 
```
pip install -r requirements.txt 
Collecting git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e (from -r requirements.txt (line 4))
  Cloning https://github.com/rmbrualla/pycolmap (to revision cc7ea4b7301720ac29287dbe450952511b32125e) to /tmp/pip-req-build-8dibjh57
  Running command git clone --filter=blob:none --quiet https://github.com/rmbrualla/pycolmap /tmp/pip-req-build-8dibjh57
  Running command git rev-parse -q --verify 'sha^cc7ea4b7301720ac29287dbe450952511b32125e'
  Running command git fetch -q https://github.com/rmbrualla/pycolmap cc7ea4b7301720ac29287dbe450952511b32125e
  Resolved https://github.com/rmbrualla/pycolmap to commit cc7ea4b7301720ac29287dbe450952511b32125e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/rahul-goel/fused-ssim@1272e21a282342e89537159e4bad508b19b34157 (from -r requirements.txt (line 22))
  Cloning https://github.com/rahul-goel/fused-ssim (to revision 1272e21a282342e89537159e4bad508b19b34157) to /tmp/pip-req-build-hb77huuz
  Running command git clone --filter=blob:none --quiet https://github.com/rahul-goel/fused-ssim /tmp/pip-req-build-hb77huuz
  Running command git rev-parse -q --verify 'sha^1272e21a282342e89537159e4bad508b19b34157'
  Running command git fetch -q https://github.com/rahul-goel/fused-ssim 1272e21a282342e89537159e4bad508b19b34157
  Running command git checkout -q 1272e21a282342e89537159e4bad508b19b34157
  Resolved https://github.com/rahul-goel/fused-ssim to commit 1272e21a282342e89537159e4bad508b19b34157
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/felix/davdev/splatting/repos/gsplat/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/felix/davdev/splatting/repos/gsplat/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/felix/davdev/splatting/repos/gsplat/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xgcxalws/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xgcxalws/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xgcxalws/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xgcxalws/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I guess it's some version issue. 
I'm using: 
```
python --version
Python 3.12.7
```
and 
```
torch.__version__
'2.5.1+cu124'
```

I dug a bit into the requirements and removing this line resolves the issue: 
```
git+https://github.com/rahul-goel/fused-ssim@1272e21a282342e89537159e4bad508b19b34157
```
meaning all other deps install fine.

**Comment by felixniemeyer** [comment]
Because ssim is required for simple_trainer.py i dug deeper and found out, that my systems cuda/nvcc version is 12.6 while pytorch was 12.4: https://github.com/rahul-goel/fused-ssim/issues/3 

will try installing pytorch nightly 12.6 now and see if it works!

**Comment by maturk** [comment]
@felixniemeyer the following conda environment works for me, not sure if it helps you out or not. 

```
# create conda environment
conda create --name gsplat -y python=3.10
conda activate gsplat
pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit

# install gsplat from source
git clone --recurse-submodules https://github.com/nerfstudio-project/gsplat
cd gsplat/
pip install -e .
```

Feel free to try newer versions of pytorch / cudatoolkit.

**Comment by felixniemeyer** [comment]
Thank you!

I'm trying to get it running in a virtualenv.

I found a way to install that `fused-ssim` dependency manually:
- make sure you have your venv setup and pytorch installed already
- clone the repo https://github.com/rahul-goel/fused-ssim
- cd into it
- run `pip install . --no-build-isolation`

I think this issue is more related to the upstream repo and the fact that I'm using this dev release of pytorch (arch's pacman providing only the most recent cuda version kind of presses me to do this). 

I'm hitting the next error now: https://github.com/nerfstudio-project/gsplat/issues/525
