### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by BladeTransformerLLC** [nerfstudio-project/gsplat#526]
Hi there,

Based on the following article I've been trying to run gsplat + mcmc + bilagrid.
https://medium.com/@heyulei/align-cameras-in-realitycapture-and-integrate-with-gaussian-splatting-gsplat-4203aa080aa0

However, when running the command python `simple_trainer.py mcmc --data_factor 1 --use_bilateral_grid --data_dir [data] --result_dir [out]` I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
Traceback (most recent call last):
  File "D:\Data\Programming\NeRFs\gsplat\examples\simple_trainer.py", line 1094, in <module>
    cli(main, cfg, verbose=True)
  File "C:\Python312\Lib\site-packages\gsplat-1.4.0-py3.12-win-amd64.egg\gsplat\distributed.py", line 360, in cli
    return _distributed_worker(0, 1, fn=fn, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\gsplat-1.4.0-py3.12-win-amd64.egg\gsplat\distributed.py", line 295, in _distributed_worker
    fn(local_rank, world_rank, world_size, args)
  File "D:\Data\Programming\NeRFs\gsplat\examples\simple_trainer.py", line 1039, in main
    runner.train()
  File "D:\Data\Programming\NeRFs\gsplat\examples\simple_trainer.py", line 551, in train
    trainloader_iter = iter(trainloader)
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\satyoshi\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    self._iterator = self._get_iterator()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\satyoshi\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\satyoshi\AppData\Roaming\Python\Python312\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Python312\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python312\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
```

My environment:
Windows 10
Python 3.12.6
PyTorch 2.4.1+cu118

**Comment by maturk** [comment]
Looks like a python error, can you try a lower python version, like 3.10? I suggest using a conda environment, where you can control all dependencies and packages installed for reproducibility. Something like the following might work well:

```
# create conda environment
conda create --name gsplat -y python=3.10
conda activate gsplat
pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit

# install gsplat from source
git clone --recurse-submodules https://github.com/nerfstudio-project/gsplat
cd gsplat/
pip install -e .
```

**Comment by maturk** [comment]
It is hard to debug, since I believe these are issues on the windows side (for both pycolmap and this error it seems). stackexchange suggests that this is a bug with pytorch on windows, and a fix is setting `num_workers=1` instead of >1 for pytorch dataloading (that uses native python multiprocessing library in the backend). I cannot personally replicate this error, since I use a linux pc.

**Comment by maturk** [comment]
@BladeTransformerLLC, cool thanks for testing. Yes this confirms my belief that this problem stems from an external issue, PyTorch/Python on Windows, and not from any code specific issue within the gsplat library.
