### ISSUE TITLE
Runtime error with `simple_trainer.py`

### ISSUE THREAD

**Issue by nickponline** [nerfstudio-project/gsplat#61]
I'm getting the following error with `simple_trainer.py`

I've tried installing with each of:
```
pip install gsplat
pip install -e .[dev]
BUILD_NO_CUDA=1 pip install -e.[dev]
```

`nickp:/mnt/mr/gsplat/examples$ python3 simple_trainer.py --img-path image.jpg`

```
Traceback (most recent call last):
  File "/mnt/d/mr/gsplat/gsplat/cuda/_backend.py", line 56, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/mnt/d/mr/gsplat/gsplat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/mr/gsplat/examples/simple_trainer.py", line 174, in <module>
    tyro.cli(main)
  File "/home/nickp/.local/lib/python3.10/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/home/nickp/.local/lib/python3.10/site-packages/tyro/_cli.py", line 449, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/nickp/.local/lib/python3.10/site-packages/tyro/_calling.py", line 216, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/mnt/d/mr/gsplat/examples/simple_trainer.py", line 166, in main
    trainer.train(
  File "/mnt/d/mr/gsplat/examples/simple_trainer.py", line 88, in train
    xys, depths, radii, conics, num_tiles_hit, cov3d = ProjectGaussians.apply(
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/d/mr/gsplat/gsplat/project_gaussians.py", line 67, in forward
    ) = _C.project_gaussians_forward(
  File "/mnt/d/mr/gsplat/gsplat/cuda/__init__.py", line 7, in call_cuda
    from ._backend import _C
  File "/mnt/d/mr/gsplat/gsplat/cuda/_backend.py", line 64, in <module>
    _C = load(
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/nickp/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gsplat_cuda': [1/6] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/backward.cu -o backward.cuda.o
/mnt/d/mr/gsplat/gsplat/cuda/csrc/backward.cu(380): warning #177-D: variable "cx" was declared but never referenced

/mnt/d/mr/gsplat/gsplat/cuda/csrc/backward.cu(381): warning #177-D: variable "cy" was declared but never referenced

[2/6] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/forward.cu -o forward.cuda.o
FAILED: forward.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/forward.cu -o forward.cuda.o
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[3/6] c++ -MMD -MF ext.o.d -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/ext.cpp -o ext.o
[4/6] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/rasterize.cu -o rasterize.cuda.o
FAILED: rasterize.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/rasterize.cu -o rasterize.cuda.o
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[5/6] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/bindings.cu -o bindings.cuda.o
FAILED: bindings.cuda.o
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/mnt/d/mr/gsplat/gsplat/cuda/csrc/third_party/glm -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/TH -isystem /home/nickp/.local/lib/python3.10/site-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -std=c++17 -c /mnt/d/mr/gsplat/gsplat/cuda/csrc/bindings.cu -o bindings.cuda.o
/mnt/d/mr/gsplat/gsplat/cuda/csrc/bindings.cu(224): warning #177-D: variable "num_cov3d" was declared but never referenced

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.
```

```
Linux CORSAIRONE 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
NVIDIA-SMI 545.23.05              Driver Version: 545.84       CUDA Version: 12.3  
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

Am I doing something wrong?

**Comment by rosejn** [comment]
You have to build with CUDA because this is a cuda implementation.  I'm building with cuda 11.7 and gcc 11.4.0 on Ubuntu linux successfully (in order to match the cuda version of the torch version I have installed).  So you might want to try with a more updated cuda, gcc, and/or torch.  My guess is that its due to the GCC or CUDA version (probably GCC).

**Comment by nickponline** [comment]
Yeah was a version mismatch thanks, for anyone wanting to run on WSL with 12.3 these are working steps:

```
# Install latest driver for Windows https://www.nvidia.com/Download/index.aspx
# wsl.exe --install
# wsl.exe --update

$ sudo apt-key del 7fa2af80
$ wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb
$ sudo dpkg -i cuda-keyring_1.1-1_all.deb
$ sudo apt-get update
$ sudo apt-get -y install cuda-toolkit-12-3
```
