### ISSUE TITLE
Strange Error in Custom Architecture

### ISSUE THREAD

**Issue by alhojel** [nerfstudio-project/gsplat#75]
So i've been trying to implement a training script / model class for 3D scenes using the 2D image example as guidance. I believe I have made all the proper adjustments. However I am getting this error:

(vip) ahojel@barreleye:/shared/ahojel/repos/volumetric/gsplat/examples$ python3 3d_trainer.py 
A
B
Iteration 0, View 0: means shape torch.Size([1, 3]), scales shape torch.Size([1, 3]), quats shape torch.Size([1, 4])
viewmat shape torch.Size([4, 4]), focal 277.77775779844205, image dimensions 200, 200, tile bounds (13, 13, 1)
Projection output: xys shape torch.Size([1, 2]), depths shape torch.Size([1]), radii shape torch.Size([1])
Spherical Harmonics output: sh_rendered shape torch.Size([1, 3])
Traceback (most recent call last):
  File "3d_trainer.py", line 222, in <module>
    tyro.cli(main)
  File "/shared/ahojel/miniconda3/envs/vip/lib/python3.8/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/shared/ahojel/miniconda3/envs/vip/lib/python3.8/site-packages/tyro/_cli.py", line 449, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/shared/ahojel/miniconda3/envs/vip/lib/python3.8/site-packages/tyro/_calling.py", line 233, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "3d_trainer.py", line 215, in main
    trainer.train(
  File "3d_trainer.py", line 130, in train
    out_img = RasterizeGaussians.apply(
  File "/shared/ahojel/miniconda3/envs/vip/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/shared/ahojel/miniconda3/envs/vip/lib/python3.8/site-packages/gsplat/rasterize.py", line 77, in forward
    background.contiguous().cuda(),
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Would you have any idea where it could come from? I uninstalled gsplats and reinstalled it but didn't work.

**Comment by liruilong940607** [comment]
Unfortunately this error message is not very informative.

But I think the way you set the `viewmat` and `projmat` is not correct. In the 2D example they are pesudo matrix, but for 3D data you want to set them up correctly. Take a look at how it is being used in nerfstudio at [here](https://github.com/nerfstudio-project/nerfstudio/blob/9e33b437dff6df5a9579c04b1eba46640df88a96/nerfstudio/models/gaussian_splatting.py#L521-L579) to get an idea.
